name: deckly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  tuple: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.8.3
  go_router: ^14.2.1
  shared_preferences: ^2.2.0
  drift: ^2.23.1
  # flutter_dynamic_icon: ^2.1.0
  flutter_blue_plus: ^1.32.4
  permission_handler: ^12.0.0+1
  flutter_ble_peripheral: ^1.2.6
  nearby_connections: ^4.3.0
  flutter_nearby_connections:
    path: ./plugins/flutter_nearby_connections
  location: ^8.0.0
  device_info_plus: ^11.4.0
  flutter_styled_toast: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  drift_dev: ^2.19.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  image: "assets/android_splash_icon.png"
  color: "#0b1344"
  android: true
  ios: true
  android_12:
    color: "#0b1344"
    image: "assets/android_splash_icon.png"
